### ISSUE TITLE
 BirthYearCalculatorMain

### ISSUE THREAD

**Issue by benn876** [raduandreipopescu/course12-homework#1]
o implementare interesanta de a obliga user-ul sa introduca datele corecte. Frumos :) 
la linia 19 doar cred ca ai uitat sa pui userAge = scanner.next()

**Comment by raduandreipopescu** [comment]
Nu am uitat.
La linia 19 fac un fel de clear la scanner pentru ca aveam o eroare si am gasit ca asta ar fi o solutie.

**Comment by benn876** [comment]
am inteles :) ok
