### ISSUE TITLE
reference escape

### ISSUE THREAD

**Issue by benn876** [raduandreipopescu/course12-homework#2]
public DaySchedule(Day day, List<String> activities) {
        this.day = day;
        this.activities = activities;
    }
   nu te-ai protejat de refrence escape aici :) Daca mai tii minte am vorbit in urma cu 2 cursuri cred. Noi trimitem doar referintele ca si parametrii adica adresele. Si cine a trimis lista activites din main poate sa o modifice si atunci iti modifica si tie state-ul din DaySchedule. De asta in momentul in care trimitem o lista ca si parametru o copiem intr-o lista noua ca sa nu folosim adresa listei pe care am primit-o

**Comment by raduandreipopescu** [comment]
Am corectat si sper sa ma invat minte :)
