### ISSUE TITLE
la Menu

### ISSUE THREAD

**Issue by benn876** [raduandreipopescu/course12-homework#3]
-> de ce ii nevoie sa trimitem scanner-ul ca si parametru si nu putem sa il instantiem direct in Menu?
 -> un pic complicata solutia dar functioneaza :) O sa incerc sa o rezolvam la curs intr-un mod mai simplu daca avem timp.
  Good job!

**Comment by raduandreipopescu** [comment]
Initial am pus scanner in metode si la final in inchideam.
Dar la close scanner se inchide si ceva de la System si nu mai merge redeschis.
De asta l-am pus in exterior.
